### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by ClementCaporal** [VolkerH/DaskFusion#3]
Hello,

Thank you for your work.
Could you add a license to the repo?

Thank you,

Clément

**Comment by ClementCaporal** [comment]
Hello @VolkerH 

I hope you are going well.
Sorry for the precedent short unclear message and for the spam.

I am a PhD student in France and we would like to use in my [laboratory (Called Laboratory for Optics and Biosciences](https://portail.polytechnique.edu/lob/en/welcome-0) your DaskFusion package. However there is no license in the repository so we don't know if we can use your code and how to properly cite it.

If you have time to add one I would be very grateful!

Thank you,

Clément

PS: Maybe the opening an issue is not a good way to do it. I can try to contact you through other channels if needed? Again, sorry for the inconvenience and spam.

**Comment by ClementCaporal** [comment]
Thank you ! Have a good day!

**Comment by VolkerH** [comment]
Thanks, I somehow missed your first notification. 
Apologies for that. I added a license.

**Comment by VolkerH** [comment]
If you want to cite it I might add a zenodo link later. This is because @m-albert  and @GenevieveBuckley who don't own the repo should also be credited (with their permission)

**Comment by VolkerH** [comment]
DOI for citation created through zenodo and added to README

**Comment by ClementCaporal** [comment]
Thank you very much!
Have a good day
